/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/App/Navbar/Basic/Action.vue')['default']
    ExternalLink: typeof import('./src/components/App/Navbar/Basic/ExternalLink.vue')['default']
    Footer: typeof import('./src/components/App/Footer.vue')['default']
    HomeTab: typeof import('./src/components/App/Navbar/Custom/HomeTab.vue')['default']
    IconAkarIconsCalendar: typeof import('~icons/akar-icons/calendar')['default']
    IconAkarIconsLocation: typeof import('~icons/akar-icons/location')['default']
    IconClarityLanguageSolid: typeof import('~icons/clarity/language-solid')['default']
    IconFaSolidAngleLeft: typeof import('~icons/fa-solid/angle-left')['default']
    IconFaSolidAngleRight: typeof import('~icons/fa-solid/angle-right')['default']
    IconFaSolidBars: typeof import('~icons/fa-solid/bars')['default']
    IconFaSolidExternalLinkAlt: typeof import('~icons/fa-solid/external-link-alt')['default']
    IconFaSolidRedo: typeof import('~icons/fa-solid/redo')['default']
    IconFaSolidTimes: typeof import('~icons/fa-solid/times')['default']
    IconIcRoundBrightness2: typeof import('~icons/ic/round-brightness2')['default']
    IconIcRoundBrightness7: typeof import('~icons/ic/round-brightness7')['default']
    IconIcRoundBrightnessAuto: typeof import('~icons/ic/round-brightness-auto')['default']
    IconMdiBookmark: typeof import('~icons/mdi/bookmark')['default']
    IconMdiBookmarkOutline: typeof import('~icons/mdi/bookmark-outline')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiFilterList: typeof import('~icons/mdi/filter-list')['default']
    IconMdiShareVariant: typeof import('~icons/mdi/share-variant')['default']
    InternalLink: typeof import('./src/components/App/Navbar/Basic/InternalLink.vue')['default']
    LanguageSwitch: typeof import('./src/components/App/Navbar/Custom/LanguageSwitch.vue')['default']
    MainContainer: typeof import('./src/components/App/MainContainer.vue')['default']
    MenuToggle: typeof import('./src/components/App/Navbar/Custom/MenuToggle.vue')['default']
    Navbar: typeof import('./src/components/App/Navbar/index.vue')['default']
    NavbarItem: typeof import('./src/components/App/Navbar/NavbarItem.vue')['default']
    NavbarItemContent: typeof import('./src/components/App/Navbar/Basic/NavbarItemContent.vue')['default']
    NavbarItemList: typeof import('./src/components/App/Navbar/NavbarItemList.vue')['default']
    NavbarMenu: typeof import('./src/components/App/Navbar/NavbarMenu.vue')['default']
    OfflineBar: typeof import('./src/components/App/OfflineBar.vue')['default']
    OlMap: typeof import('./src/components/Map/OlMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleItem: typeof import('./src/components/Session/ScheduleItem.vue')['default']
    ScheduleList: typeof import('./src/components/Session/ScheduleList.vue')['default']
    ScheduleNavbar: typeof import('./src/components/Session/ScheduleNavbar.vue')['default']
    ScheduleTable: typeof import('./src/components/Session/ScheduleTable.vue')['default']
    ScheduleTableRoomCell: typeof import('./src/components/Session/ScheduleTableRoomCell.vue')['default']
    SessionFilter: typeof import('./src/components/Session/SessionFilter.vue')['default']
    SponsorFooter: typeof import('./src/components/App/SponsorFooter.vue')['default']
    ThemeToggle: typeof import('./src/components/App/Navbar/Custom/ThemeToggle.vue')['default']
  }
}
