// !WARNING! This file is auto-generated by /scripts/generateLanguagesImport.ts, so all your modifications would be replaced.

import en from './en.json'
import zhTw from './zh-TW.json'

export type LanguageType = 'en' | 'zh-TW'

export const defaultLanguageType: LanguageType = 'zh-TW'

export const availableLanguageTypes: LanguageType[] = ['en', 'zh-TW']

export type LanguagePack = typeof zhTw

export type LanguagePackSet = {
  [languageType in LanguageType]: LanguagePack
}

export const languagePackSet: LanguagePackSet = {
  en: en,
  'zh-TW': zhTw
}
